# Use Node.js version 22 as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to install dependencies
COPY package*.json ./

# Install any necessary dependencies
RUN npm install

# Copy the rest of the application files into the container
COPY . .

# Expose the port your app will run on (in this case, 2036)
EXPOSE 2037

# Command to run your application
CMD ["node", "index.js"]